sonar.projectKey=26.1_Java:master
sonar.projectName=26.1_Java
sonar.projectVersion=4.0
sonar.sources=.
#sonar.sourceEncoding=UTF-8
#sonar.java.source=17
sonar.java.binaries=target/classes
sonar.host.url=http://172.27.59.89:9000/
#sonar.exclusions=**/*.xml,**/*.yml,**/*.yaml
#for sonar.cybage.com
#sonar.login=squ_0abb8761b21b1c30a2440fb0d4ec103db2a6c519 
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.login=squ_6d0c59f9c60edf0532f575e5479cb5649468855e
