name: Build

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  code-quality: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build + Test
        run: mvn clean verify

      # Generates:
      # target/site/jacoco/jacoco.xml

      - name: Convert JaCoCo to Cobertura
        uses: haynes/jacoco2cobertura-action@v1.0

      - name: Upload coverage
        uses: actions/upload-code-coverage@v1
        with:
          files: cobertura.xml
